### ISSUE TITLE
wireless-tools is deprecated

### ISSUE THREAD

**Issue by nicola-lunghi** [varigit/meta-variscite-fsl-community#14]
https://github.com/varigit/meta-variscite-fslc/blob/a6322295a39341fe56e25c6b23f5e01cabbd8173/recipes-connectivity/ti-compat-wireless/ti-compat-wireless-wl18xx.bb#L10

see here

https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=f7137f94905c0d0ef1c0af8e53db18de00a17fec

**Comment by varigigi** [comment]
Ciao Nicola,
thanks for notifying the poky commit, but actually we are not expecting any impact on our repository.
Poky commit is only available in Thud and I'm not expecting any backporting.
Starting from Rocko, we do no longer reference ti-compat-wireless-wl18xx in any recipe, so upon your notification, we simply removed it.
For previous releases, up to Pyro, ti-compat-wireless-wl18xx is mandatory, but I'm not expecting any change in poky repositories.
For faster support request management, please contact us through the customer portal:
https://varisciteportal.axosoft.com/login
Thanks
BR
Pier
