### ISSUE TITLE
dart6ul thud no wifi on image with systemd

### ISSUE THREAD

**Issue by razvan-becheriu** [varigit/meta-variscite-fsl-community#23]
Hi,

I have build a thud image with init.d and the wifi drivers are loaded and working, but when I build with systemd, there is no wifi and the kernel complains about the driver.

I am running:
    bitbake fsl-image-gui
    bitbake var-image-swupdate
    bitbake var-image-swu

Can you verify?

on init.d:
brcmfmac: brcmf_fw_map_chip_to_name: using brcm/brcmfmac4339-sdio.bin for chip 0x004339(17209) rev 0x000002
brcmfmac mmc0:0001:1: Falling back to user helper
brcmfmac: brcmf_c_process_clm_blob: no clm_blob available(err=-11), device may have limited channels available
brcmfmac: brcmf_c_preinit_dcmds: Firmware version = wl0: Jun 26 2018 01:58:05 version 6.37.39.94 (r692107 CY)
WIFI startup success 

on systemd:
brcmfmac: brcmf_c_process_clm_blob: no clm_blob available(err=-2), device may have limited channels available
Unable to handle kernel NULL pointer dereference at virtual address 00000118
pgd = 80004000
[00000118] *pgd=00000000
Internal error: Oops: 17 [#1] PREEMPT SMP ARM
Modules linked in: brcmfmac brcmutil imx_sdma virt_dma
CPU: 0 PID: 84 Comm: kworker/0:3 Not tainted 4.14.78-mx6ul+gc228d86 #1
Hardware name: Freescale i.MX6 UltraLite (Device Tree)
Workqueue: events request_firmware_work_func
task: 9c357000 task.stack: 9c5d4000
task: 9c357000 task.stack: 9c5d4000
PC is at mutex_lock+0x14/0x3c
LR is at brcmf_fil_iovar_data_get+0x2c/0xbc [brcmfmac]
pc : [<809984c4>]    lr : [<7f027398>]    psr: 600e0013
sp : 9c5d5c90  ip : 00726576  fp : 00000001
r10: 00000008  r9 : 7f03e210  r8 : 00000100
r7 : 9c5d5d18  r6 : 9dc19d00  r5 : 00000118  r4 : 0000012c
r3 : 9c357000  r2 : 9c5d5d18  r1 : 7f03e210  r0 : 00000118
Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
Control: 10c53c7d  Table: 9dd0c06a  DAC: 00000051
Process kworker/0:3 (pid: 84, stack limit = 0x9c5d4210)
Stack: (0x9c5d5c90 to 0x9c5d6000)
5c80:                                     9dc19d00 9dc19d00 9cf18000 9dc19d00
5ca0: 9cf18000 00000000 00000001 9dc24a40 00000002 7f02aa34 9c5d5d68 00000000
5cc0: 00000002 00000000 9c5d4000 00000001 00004001 000014e4 000043ae 92069000
5ce0: 00000001 0000002e 000006c5 000014e4 00001203 0625275e 00000000 00000000
5d00: 00004339 0000000b 00000006 00000000 00000002 000642cc 00726576 00000000
5d20: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
5d40: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
5d60: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
5d80: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
5da0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
5dc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
5de0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
5e00: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 9cf18000
5e20: 9dc19d00 7f02c660 7f03e760 00000000 00000000 9cb33000 9cb58c00 9dd73808
5e40: 00000001 00000001 00000002 7f034730 000008e0 00000001 00000000 00000000
5e60: 9cef7500 00000000 80ff694c 9dc24f40 7f0343c0 9cc8a000 9cc8a000 00000000
5e80: 00000000 9fbd7bc0 9cd6f2c0 7f02d0d8 000008e0 8051bf6c 9cd6f280 9cd6f2c0
5ea0: 9cef7500 9c5d5f1c 00000000 80fe17dc 80a5c57c 8051c924 7fffffff 00000000
5ec0: 00000001 00000000 a4a95000 9cc8a000 000008d8 00000068 00000001 00000938
5ee0: 0000092b 00010000 9fbd7bc0 9cd6f240 9c5ba480 9fbd7bc0 9fbdab00 00000000
5f00: 00000000 9fbd7bc0 ffffe000 8051ce6c 00000000 00000007 ffffe000 9cd6f2c0
5f20: 9cd6f240 80140e08 00000008 80f02d00 9c5ba480 9c5ba498 9fbd7bc0 00000008
5f40: 80f02d00 9fbd7bd8 9fbd7bc0 80141a9c ffffe000 80f96ebc 80c16de0 00000000
5f60: ffffe000 9c5bb640 9c5bb340 00000000 9c5d4000 9c5ba480 80141a4c 9c063ec8
5f80: 9c5bb65c 801468f8 9c5d4000 9c5bb340 801467ac 00000000 00000000 00000000
5fa0: 00000000 00000000 00000000 80107a48 00000000 00000000 00000000 00000000
5fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
5fe0: 00000000 00000000 00000000 00000000 00000013 00000000 00000000 00000000
[<809984c4>] (mutex_lock) from [<7f027398>] (brcmf_fil_iovar_data_get+0x2c/0xbc [brcmfmac])
[<7f027398>] (brcmf_fil_iovar_data_get [brcmfmac]) from [<7f02aa34>] (brcmf_c_preinit_dcmds+0x12c/0x44c [brcmfmac])
[<7f02aa34>] (brcmf_c_preinit_dcmds [brcmfmac]) from [<7f02c660>] (brcmf_bus_started+0x64/0x28c [brcmfmac])
[<7f02c660>] (brcmf_bus_started [brcmfmac]) from [<7f034730>] (brcmf_sdio_firmware_callback+0x370/0x6ac [brcmfmac])
[<7f034730>] (brcmf_sdio_firmware_callback [brcmfmac]) from [<7f02d0d8>] (brcmf_fw_request_nvram_done+0x190/0x6d4 [brcmfmac])
[<7f02d0d8>] (brcmf_fw_request_nvram_done [brcmfmac]) from [<8051ce6c>] (request_firmware_work_func+0x3c/0x64)
[<8051ce6c>] (request_firmware_work_func) from [<80140e08>] (process_one_work+0x1d8/0x410)
[<80140e08>] (process_one_work) from [<80141a9c>] (worker_thread+0x50/0x598)
[<80141a9c>] (worker_thread) from [<801468f8>] (kthread+0x14c/0x154)
[<801468f8>] (kthread) from [<80107a48>] (ret_from_fork+0x14/0x2c)
Code: e3c33d7f e3c3303f e593300c f590f000 (e1901f9f)
---[ end trace 3adeed9f6dd268af ]---
brcmfmac: brcmf_c_process_clm_blob: no clm_blob available(err=-2), device may have limited channels available
Unable to handle kernel NULL pointer dereference at virtual address 00000010
pgd = 80004000
[00000010] *pgd=00000000
Internal error: Oops: 17 [#2] PREEMPT SMP ARM
Modules linked in: brcmfmac brcmutil imx_sdma virt_dma
CPU: 0 PID: 610 Comm: kworker/0:4 Tainted: G      D         4.14.78-mx6ul+gc228d86 #1
Hardware name: Freescale i.MX6 UltraLite (Device Tree)
Workqueue: events request_firmware_work_func
task: 9c321800 task.stack: 9dd92000
PC is at brcmf_fil_cmd_data+0x14/0x94 [brcmfmac]
LR is at 0x0
pc : [<7f026f8c>]    lr : [<00000000>]    psr: 200e0113
sp : 9dd93c80  ip : 9d950000  fp : 00000001
r10: 00000008  r9 : 7f03e210  r8 : 00000100
r7 : 9dd93d18  r6 : 9dc1a500  r5 : 9d950118  r4 : 00000000
r3 : 00000104  r2 : 9d95012c  r1 : 00000106  r0 : 9dc1a500
Flags: nzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
Control: 10c53c7d  Table: 9dd0c06a  DAC: 00000051
Process kworker/0:4 (pid: 610, stack limit = 0x9dd92210)
Stack: (0x9dd93c80 to 0x9dd94000)
3c80: 00000100 7f03e210 9d95012c 7f0273cc 00000000 9dc1a500 9d950000 9dc1a500
3ca0: 9d950000 00000000 00000001 9caef700 00000002 7f02aa34 9dd93d68 00000000
3cc0: 00000002 00000000 9dd92000 00000001 00207000 000014e4 000043ae 92069000
3ce0: 00000001 0000002e 000006c5 000014e4 00001203 0625275e 00000000 00000000
3d00: 00004339 0000000b 00000006 00000000 00000002 000642cc 00726576 00000000
3d20: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3d40: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3d60: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3d80: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3da0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3dc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3de0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3e00: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 9d950000
3e20: 9dc1a500 7f02c660 7f03e760 00000000 00000000 9cafa400 9cafa800 9d965208
3e40: 00000001 00000001 00000002 7f034730 000008e0 00000001 00000000 00000000
3e60: 9cef7a80 00000000 80ff694c 9dc24300 7f0343c0 9cc8a000 9cc8a000 00000000
3e80: 00000000 9fbd7bc0 9dc24940 7f02d0d8 000008e0 8051bf6c 9dc24ec0 9dc24940
3ea0: 9cef7a80 9dd93f1c 00000000 80fe17dc 80a5c57c 8051c924 7fffffff 00000000
3ec0: 00000001 00000000 a4aa5000 9cc8a000 000008d8 00000068 00000001 00000938
3ee0: 0000092b 00010000 9c154a10 9dc24f00 9d958580 9fbd7bc0 9fbdab00 00000000
3f00: 00000000 9fbd7bc0 ffffe000 8051ce6c 00000000 00000007 ffffe000 9dc24940
3f20: 9dc24f00 80140e08 00000008 80f02d00 9d958580 9d958598 9fbd7bc0 00000008
3f40: 80f02d00 9fbd7bd8 9fbd7bc0 80141a9c ffffe000 80f96ebc 80c16de0 00000000
3f60: ffffe000 9caa1f80 9caa15c0 00000000 9dd92000 9d958580 80141a4c 9c063ec8
3f80: 9caa1f9c 801468f8 9dd92000 9caa15c0 801467ac 00000000 00000000 00000000
3fa0: 00000000 00000000 00000000 80107a48 00000000 00000000 00000000 00000000
3fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3fe0: 00000000 00000000 00000000 00000000 00000013 00000000 00000000 00000000
[<7f026f8c>] (brcmf_fil_cmd_data [brcmfmac]) from [<7f0273cc>] (brcmf_fil_iovar_data_get+0x60/0xbc [brcmfmac])
[<7f0273cc>] (brcmf_fil_iovar_data_get [brcmfmac]) from [<7f02aa34>] (brcmf_c_preinit_dcmds+0x12c/0x44c [brcmfmac])
[<7f02aa34>] (brcmf_c_preinit_dcmds [brcmfmac]) from [<7f02c660>] (brcmf_bus_started+0x64/0x28c [brcmfmac])
[<7f02c660>] (brcmf_bus_started [brcmfmac]) from [<7f034730>] (brcmf_sdio_firmware_callback+0x370/0x6ac [brcmfmac])
[<7f034730>] (brcmf_sdio_firmware_callback [brcmfmac]) from [<7f02d0d8>] (brcmf_fw_request_nvram_done+0x190/0x6d4 [brcmfmac])
[<7f02d0d8>] (brcmf_fw_request_nvram_done [brcmfmac]) from [<8051ce6c>] (request_firmware_work_func+0x3c/0x64)
[<8051ce6c>] (request_firmware_work_func) from [<80140e08>] (process_one_work+0x1d8/0x410)
[<80140e08>] (process_one_work) from [<80141a9c>] (worker_thread+0x50/0x598)
[<80141a9c>] (worker_thread) from [<801468f8>] (kthread+0x14c/0x154)
[<801468f8>] (kthread) from [<80107a48>] (ret_from_fork+0x14/0x2c)
Code: e24dd008 e590c000 e5dd4010 e59ce000 (e59ee010)
---[ end trace 3adeed9f6dd268b0 ]---
sysfs group 'power' not found for kobject 'brcm!brcmfmac4339-sdio.clm_blob'
Modules linked in: brcmfmac brcmutil imx_sdma virt_dma
CPU: 0 PID: 83 Comm: kworker/0:2 Tainted: G      D         4.14.78-mx6ul+gc228d86 #1
Hardware name: Freescale i.MX6 UltraLite (Device Tree)
Workqueue: events request_firmware_work_func
[<8010f770>] (unwind_backtrace) from [<8010b278>] (show_stack+0x10/0x14)
[<8010b278>] (show_stack) from [<8098355c>] (dump_stack+0x78/0x8c)
[<8098355c>] (dump_stack) from [<8012aa50>] (__warn+0xe4/0x100)
[<8012aa50>] (__warn) from [<8012a6c8>] (warn_slowpath_fmt+0x38/0x48)
[<8012a6c8>] (warn_slowpath_fmt) from [<80274ef4>] (sysfs_remove_group+0x94/0x9c)
[<80274ef4>] (sysfs_remove_group) from [<80501568>] (device_del+0xec/0x32c)
[<80501568>] (device_del) from [<8051cbac>] (_request_firmware+0x5c4/0x6cc)
[<8051cbac>] (_request_firmware) from [<8051ccf0>] (request_firmware+0x3c/0x54)
[<8051ccf0>] (request_firmware) from [<7f02a710>] (brcmf_c_process_clm_blob+0x54/0x24c [brcmfmac])
[<7f02a710>] (brcmf_c_process_clm_blob [brcmfmac]) from [<7f02a9fc>] (brcmf_c_preinit_dcmds+0xf4/0x44c [brcmfmac])
[<7f02a9fc>] (brcmf_c_preinit_dcmds [brcmfmac]) from [<7f02c660>] (brcmf_bus_started+0x64/0x28c [brcmfmac])
[<7f02c660>] (brcmf_bus_started [brcmfmac]) from [<7f034730>] (brcmf_sdio_firmware_callback+0x370/0x6ac [brcmfmac])
[<7f034730>] (brcmf_sdio_firmware_callback [brcmfmac]) from [<7f02d0d8>] (brcmf_fw_request_nvram_done+0x190/0x6d4 [brcmfmac])
[<7f02d0d8>] (brcmf_fw_request_nvram_done [brcmfmac]) from [<8051ce6c>] (request_firmware_work_func+0x3c/0x64)
[<8051ce6c>] (request_firmware_work_func) from [<80140e08>] (process_one_work+0x1d8/0x410)
[<80140e08>] (process_one_work) from [<80141a9c>] (worker_thread+0x50/0x598)
[<80141a9c>] (worker_thread) from [<801468f8>] (kthread+0x14c/0x154)
[<801468f8>] (kthread) from [<80107a48>] (ret_from_fork+0x14/0x2c)
---[ end trace 3adeed9f6dd268b1 ]---
brcmfmac: brcmf_c_process_clm_blob: no clm_blob available(err=-11), device may have limited channels available
Unable to handle kernel NULL pointer dereference at virtual address 00000118
pgd = 80004000
[00000118] *pgd=00000000
Internal error: Oops: 17 [#3] PREEMPT SMP ARM
Modules linked in: brcmfmac brcmutil imx_sdma virt_dma
CPU: 0 PID: 83 Comm: kworker/0:2 Tainted: G      D W       4.14.78-mx6ul+gc228d86 #1
Hardware name: Freescale i.MX6 UltraLite (Device Tree)
Workqueue: events request_firmware_work_func
task: 9c356a00 task.stack: 9c5d2000
PC is at mutex_lock+0x14/0x3c
LR is at brcmf_fil_iovar_data_get+0x2c/0xbc [brcmfmac]
pc : [<809984c4>]    lr : [<7f027398>]    psr: 60070013
sp : 9c5d3c90  ip : 00726576  fp : 00000001
r10: 00000008  r9 : 7f03e210  r8 : 00000100
r7 : 9c5d3d18  r6 : 9c827500  r5 : 00000118  r4 : 0000012c
r3 : 9c356a00  r2 : 9c5d3d18  r1 : 7f03e210  r0 : 00000118
Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
Control: 10c53c7d  Table: 9cce006a  DAC: 00000051
Process kworker/0:2 (pid: 83, stack limit = 0x9c5d2210)
Stack: (0x9c5d3c90 to 0x9c5d4000)
3c80:                                     9c827500 9c827500 9cefc000 9c827500
3ca0: 9cefc000 00000000 00000001 9ceacf80 00000002 7f02aa34 f4a0200c f4a02000
3cc0: 00000000 9c355280 9fbd7fc0 9fbd7ff8 80f03ea0 000014e4 000043ae 92069000
3ce0: 00000001 0000002e 000006c5 000014e4 00001203 0625275e 00000000 00000000
3d00: 00004339 0000000b 00000006 00000000 00000002 000642cc 00726576 00000000
3d20: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3d40: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3d60: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3d80: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3da0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3dc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3de0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3e00: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 9cefc000
3e20: 9c827500 7f02c660 7f03e760 00000000 00000000 9cb43c00 9cb5ec00 9cb31a08
3e40: 00000001 00000001 00000002 7f034730 000008e0 ffffe000 000102a8 00000000
3e60: 9fbd7bc0 00000000 00000001 9ceac440 7f0343c0 9cc8b000 9cc8b000 00000000
3e80: 00000000 9fbd7bc0 9cd97840 7f02d0d8 000008e0 8051bf6c 9cd97800 9cd97840
3ea0: 9ce40180 9c5d3f1c 00000000 80fe17dc 80a5c57c 8051c924 7fffffff 00000000
3ec0: 00000001 00000000 a4a35000 9cc8b000 000008d8 00000068 00000001 00000938
3ee0: 0000092b 00010000 ffffe000 9cd977c0 9c5a1d80 9fbd7bc0 9fbdab00 00000000
3f00: 00000000 9fbd7bc0 ffffe000 8051ce6c 00000000 00000007 ffffe000 9cd97840
3f20: 9cd977c0 80140e08 00000008 80f02d00 9c5a1d80 9c5a1d98 9fbd7bc0 00000008
3f40: 80f02d00 9fbd7bd8 9fbd7bc0 80141a9c ffffe000 80f96ebc 80c16de0 00000000
3f60: ffffe000 9c5b07c0 9c5b0740 00000000 9c5d2000 9c5a1d80 80141a4c 9c063ec8
3f80: 9c5b07dc 801468f8 9c5d2000 9c5b0740 801467ac 00000000 00000000 00000000
3fa0: 00000000 00000000 00000000 80107a48 00000000 00000000 00000000 00000000
3fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
3fe0: 00000000 00000000 00000000 00000000 00000013 00000000 00000000 00000000
[<809984c4>] (mutex_lock) from [<7f027398>] (brcmf_fil_iovar_data_get+0x2c/0xbc [brcmfmac])
[<7f027398>] (brcmf_fil_iovar_data_get [brcmfmac]) from [<7f02aa34>] (brcmf_c_preinit_dcmds+0x12c/0x44c [brcmfmac])
[<7f02aa34>] (brcmf_c_preinit_dcmds [brcmfmac]) from [<7f02c660>] (brcmf_bus_started+0x64/0x28c [brcmfmac])
[<7f02c660>] (brcmf_bus_started [brcmfmac]) from [<7f034730>] (brcmf_sdio_firmware_callback+0x370/0x6ac [brcmfmac])
[<7f034730>] (brcmf_sdio_firmware_callback [brcmfmac]) from [<7f02d0d8>] (brcmf_fw_request_nvram_done+0x190/0x6d4 [brcmfmac])
[<7f02d0d8>] (brcmf_fw_request_nvram_done [brcmfmac]) from [<8051ce6c>] (request_firmware_work_func+0x3c/0x64)
[<8051ce6c>] (request_firmware_work_func) from [<80140e08>] (process_one_work+0x1d8/0x410)
[<80140e08>] (process_one_work) from [<80141a9c>] (worker_thread+0x50/0x598)
[<80141a9c>] (worker_thread) from [<801468f8>] (kthread+0x14c/0x154)
[<801468f8>] (kthread) from [<80107a48>] (ret_from_fork+0x14/0x2c)
Code: e3c33d7f e3c3303f e593300c f590f000 (e1901f9f) 
---[ end trace 3adeed9f6dd268b2 ]---

Thank you,
Razvan

**Comment by eranmati** [comment]
Hi Razvan.
I can reproduce the issue, and looks like it was introduced by the upgrade to systemd 239 in poky.
After replacing the systemd recipe with version 237 it works again.
We'll investigate further in a few days and update.

Thanks for the feedback.
(Next time, please use the Variscite customer portal, though)

Regards,
Eran

**Comment by razvan-becheriu** [comment]
Thank you Eran for confirming this,

Razvan

**Comment by razvan-becheriu** [comment]
Hi,

Any update on this?
I have created a user account, but I am still waiting for confirmation and account activation.

Thank you,
Razvan

**Comment by eranmati** [comment]
Sorry, it will take some time to get to it.
In the mean time you can revert the systemd recipe to version 237, like I wrote before.

Regards,
Eran

**Comment by razvan-becheriu** [comment]
OK. Thank you.
Please let me know when the issue is fixed.
I'll use sumo for now.

Regards,
Razvan

**Comment by eranmati** [comment]
Hi Razvan.
Disabling CONFIG_FW_LOADER_USER_HELPER_FALLBACK in the kernel configuration fixes the issue.
We will push the fix soon.

Regards,
Eran

**Comment by eranmati** [comment]
Fix pushed:
https://github.com/varigit/meta-variscite-fslc/commit/73bd1c1360d923d79c557850d6818756c5a85542

Regards,
Eran

**Comment by razvan-becheriu** [comment]
Thank you!

Best Regards,
Razvan
