### ISSUE TITLE
Default branch

### ISSUE THREAD

**Issue by johannesschrimpf** [varigit/meta-variscite-fsl-community#24]
I suggest setting the default branch to the newest version of the repo. Now it's on morty, which is from 2016 and quite outdated. A likely even better alternative could be a master branch with work-in-progress updates, since the developers who access the github repo here likely are the more experiences users who are not using the pre-defined package structure and are experimenting with different setups, as well could contribute with bug-fixes before an official release is posted.

**Comment by dileepsloki1** [comment]
How to use meta-variscite-fslc layer of branch Dunfell with Poky of Kirkstone....? Can we have meta-variscite-fslc layer explicit for Kirikstone ?

**Comment by eranmati** [comment]
@dileepsloki1, we will release new branches for Kirkstone soon.
meta-variscite-fslc will not be part of our Yocto Kirkstone release, though (it is not part of our released Yocto Hardknott either).
Our latest Yocto release uses the following meta layers instead:
https://github.com/varigit/meta-variscite-bsp
https://github.com/varigit/meta-variscite-sdk
https://github.com/varigit/meta-variscite-hab

You should follow https://variwiki.com or https://github.com/varigit/variscite-bsp-platform/releases for the releases for each of our SOMs.
See also the "How to subscribe to Variscite’s GitHub repositories to get real-time notifications" post on the Variscite blog: https://www.variscite.com/blog/how-to-subscribe-to-variscites-github-repositories-to-get-real-time-notifications/

Regards,
Eran

**Comment by dileepsloki1** [comment]
Thanks a lot for quick response

**Comment by cmorganBE** [comment]
Any updates on kirkstone release?

**Comment by nsdrude** [comment]
@cmorganBE we already released Kirkstone for the VAR-SOM-MX8M-PLUS and DART-MX8M-PLUS and are currently working on the rest of the i.MX8/8X/8M family. Please watch for new releases by following what @eranmati [wrote](https://github.com/varigit/meta-variscite-fslc/issues/24#issuecomment-1177302295).

**Comment by cmorganBE** [comment]
@nsdrude ahh k, didn't realize you had split the layer up. Thanks for the pointer.
