### ISSUE TITLE
freertos-variscite.inc

### ISSUE THREAD

**Issue by mmitchel** [varigit/meta-variscite-fsl-community#25]
Does not pass QA when using "usrmerge" DISTRO feature. The feature is used when the OTA updater is ostree and not swupdate.

ERROR: freertos-variscite-2.9.x-r0 do_package_qa: QA Issue: freertos-variscite package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]

**Comment by mmitchel** [comment]
changes are to remove literal uses of /lib and replace with ${base_libdir} within do_install() and FILES_${PN} as needed

**Comment by nsdrude** [comment]
@mmitchel Thanks for reporting this, I've been able to reproduce it. I'll push a series of patches to fix this (and the other similar issues you reported) in the coming days.

Next time, please use Variscite's customer portal.

Thanks,
Nate

**Comment by nsdrude** [comment]
@mmitchel please see: https://github.com/varigit/meta-variscite-fslc/commit/4b41f5e4d3fa73e7037ce8b275239668c23421eb
