### ISSUE TITLE
bcm43xx-utils.bb

### ISSUE THREAD

**Issue by mmitchel** [varigit/meta-variscite-fsl-community#26]
Does not pass QA when using "usrmerge" DISTRO feature. The feature is used when the OTA updater is ostree and not swupdate.

ERROR: bcm43xx-utils-1.0-r0 do_package: QA Issue: bcm43xx-utils: Files/directories were installed but not shipped in any package:

**Comment by mmitchel** [comment]
changes are to remove literal uses of /lib and replace with ${base_libdir} within do_install() and FILES_${PN} as needed

**Comment by nsdrude** [comment]
@mmitchel thanks for reporting, please see: https://github.com/varigit/meta-variscite-fslc/commit/2140af47b91399b59135d6e67728453988557570
