### ISSUE TITLE
fsl-image-gui.bb

### ISSUE THREAD

**Issue by mmitchel** [varigit/meta-variscite-fsl-community#27]
Fails during do_image() when using "usrmerge" DISTRO feature. The feature is used when the OTA updater is ostree and not swupdate.

Exception: bb.process.ExecutionError: Execution of '/build/repo/var-fslc-yocto/build_xwayland/tmp/work/imx8qm_var_som-fslc-linux/fsl-image-gui/1.0-r0/temp/run.systemd_disable_vt.4015395' failed with exit code 1:
rm: cannot remove '/build/repo/var-fslc-yocto/build_xwayland/tmp/work/imx8qm_var_som-fslc-linux/fsl-image-gui/1.0-r0/rootfs/usr/etc/systemd/system/getty.target.wants/getty@tty*.service': No such file or directory

**Comment by mmitchel** [comment]
within systemd_disable_vt () change the "rm" command to "rm -f" as the files are not installed, force rm returns no error. no getty@tty*.service is installed, so original command bombs out.

**Comment by nsdrude** [comment]
@mmitchel thanks for reporting, please see: https://github.com/varigit/meta-variscite-fslc/commit/9c909ec98cac92bfa901761c8035d186584f9f72
