### ISSUE TITLE
Avahi damon not started 

### ISSUE THREAD

**Issue by dpatil89** [varigit/meta-variscite-fsl-community#29]
I am using Linux Kernel version 5.4.85.
I successfully created and run core-minimal-image on imx7d evk.
Avahi is available in /etc/passwd and /etc/groups.
When following command is given 
**/etc/init.d/avahi-daemon start**
It gives following error
**15:19:43 imx7-var-som daemon.err avahi-daemon[500]: Failed to find user 'avahi'.
   15:19:43 imx7-var-som daemon.err avahi-daemon[500]: Failed to find user 'avahi'.
   15:19:43 imx7-var-som daemon.err avahi-daemon[500]: Failed to find user 'avahi'.**

Is anything required to add in core-image-minimal to find avahi user?
I remove avahi entry in /etc/passwd and /etc/groups and add manually avai user still problem exist.

I tried login on customer support portal but didn't get access.

**Comment by varigigi** [comment]
@dpatil89, following the support in our ticketing system I'm now closing this issue.
As verified, when building the core-image-minimal, several packages are missing.
Adding avahi packages on top of core-image-minimal, is not enough for making avahi-daemon working correctly.
The same behavior is not reproducible adding avahi packages on top of core-image-base.
This is just a matter of dependencies identification: meta-variscite layer does not remove any package.

**Comment by dpatil89** [comment]
Hello varigigi,
I also tried with core-image-base and added avahi daemon package but it didn't work.
Could you give me manifest file available in your tmp/deploy/image/${machine}/ directory
I will compare and figure out which package is missing ?

Regards,
Dhananjay Patil
