### ISSUE TITLE
Missing imx_v7_var_defconfig

### ISSUE THREAD

**Issue by xtovski** [varigit/meta-variscite-fsl-community#30]
Branch: hardknott
Machine: var-som-mx6

Referenced

https://github.com/varigit/meta-variscite-fslc/blob/eff54271f37b78a7d5e751b3dbbef0e67bd40582/recipes-kernel/linux/linux-common.inc#L1-L4

Does not contain `imx_v7_var_defconfig` producing build failure.
In fact it contains `imx_v7_defconfig` so maybe its a typo.

https://github.com/varigit/meta-variscite-fslc/blob/eff54271f37b78a7d5e751b3dbbef0e67bd40582/recipes-kernel/linux/linux-variscite_5.4.bb#L32

**Comment by xtovski** [comment]
Link to referenced directory in question:
https://github.com/varigit/linux-imx/tree/5.4-2.3.x-imx_var01/arch/arm/configs

**Comment by xtovski** [comment]
The issue is temporarily fixed with changing
```
#meta-variscite-fslc/recipes-kernel/linux/linux-common.inc

LINUX_VERSION = "5.4.85"
SRCBRANCH = "5.4-2.1.x-imx_var01"
SRCREV = "343970224e3d8a10acdb2a6c8483c5328235196b"
KERNEL_SRC = "git://github.com/varigit/linux-imx;protocol=git"
```

**Comment by eranmati** [comment]
Hi @xtovski.
We did not yet officially release Yocto Hardknott for the VAR-SOM-MX6.
Please see the following for our official VAR-SOM-MX6 SW releases: https://variwiki.com/index.php?title=VAR-SOM-MX6
