### ISSUE TITLE
Where is u-boot-fw-utils.bb on dunfell branch?

### ISSUE THREAD

**Issue by leonardoheld** [varigit/meta-variscite-fsl-community#31]
Hi :) 

I want to use fw-utils to set and read some variables from userspace. For that I need to specify the storage medium and the addresses in `fw_env.config` in - I assume - the fw-utils recipe for dunfell. But I found no recipe in the folder.

Regards.

**Comment by nsdrude** [comment]
@leonheld please see https://github.com/varigit/meta-variscite-fslc/commit/51fa5225035013ce897f38a607edb8498593e195

In the future, please use Variscite's [Customer Support Portal](https://www.variscite.com/support/)

**Comment by leonardoheld** [comment]
Thanks for the pointer! It worked alright just editing the `fw_env.config` file with

```
# Block device example
/dev/mmcblk1            0xE0000		0x2000

**Comment by eranmati** [comment]
@leonheld, note that we already provide a fw_env.config with the default values for working on an SD card, and if you use our "recovery"/"extended" SD card and our install_yocto.sh script to install Yocto to the eMMC, then the script will adjust the fw_env.config on the eMMC automatically, to point to the env. on the eMMC.
