### ISSUE TITLE
Bitbake warning about linux-variscite

### ISSUE THREAD

**Issue by yakuporhan** [varigit/meta-variscite-fsl-community#32]
Hi,
There is a warning message while bitbake fsl-image-gui. It should be related with kernel configs. Could you check if it matters? Thanks...

WARNING: linux-variscite-5.4.127+gitAUTOINC+7ab6e3c4cf-r0 do_kernel_configcheck: [kernel config]: specified values did not make it into the kernel's final configuration:
  [NOTE]: 'CONFIG_MXC_GPU_VIV' last val (m) and .config val (n) do not match
  [INFO]: CONFIG_MXC_GPU_VIV : n ## .config: 6595 :configs///defconfig (m) 
  [INFO]: raw config text:
    config MXC_GPU_VIV
     tristate "MXC Vivante GPU support"
     default y
     depends on ARCH_MXC
     help
       Say Y to get the GPU driver support.
    Config 'MXC_GPU_VIV' has the following Direct dependencies (MXC_GPU_VIV=y):
            ARCH_MXC(=y)
    Parent dependencies are:
         ARCH_MXC [y]

**Comment by nsdrude** [comment]
@yakuporhan can you please provide the steps to reproduce this?

**Comment by yakuporhan** [comment]
I have just followed instructions on variscite wiki page for imx8mmini -> https://variwiki.com/index.php?title=Yocto_Build_Release&release=RELEASE_HARDKNOTT_V1.1_DART-MX8M-MINI
I downloaded latest repos -> repo init -u https://github.com/varigit/variscite-bsp-platform.git -b refs/tags/hardknott-fslc-5.4-2.3.x-mx8mm-v1.1 -m default.xml
Then, selected right machine ->MACHINE=imx8mm-var-dart DISTRO=fslc-xwayland . setup-environment build_xwayland
Finally started bitbake process -> bitbake fsl-image-gui
That's all.

**Comment by yakuporhan** [comment]
Hi,
It may be caused by kernel .config file. Because MXC_GPU_VIV value is NOT set in .config file(commented) however set as "m" in defconfig file. So do_kernel_configcheck process may be complaining this situation. .config and defconfig files are the default files which I have not modified yet.

**Comment by nsdrude** [comment]
This warning can be ignored. `CONFIG_MXC_GPU_VIV` is removed from .config by: [fsl-vivante-kernel-driver-handler.bbclass#L56-L58](https://github.com/Freescale/meta-freescale/blob/hardknott/classes/fsl-vivante-kernel-driver-handler.bbclass#L56-L58)

And then provided by: [kernel-module-imx-gpu-viv_6.4.3.p2.0.bb](https://github.com/Freescale/meta-freescale/blob/hardknott/recipes-kernel/kernel-modules/kernel-module-imx-gpu-viv_6.4.3.p2.0.bb)

This warning is not present in our Dunfell release, and is not present in later Hardknott releases. After researching why, It appears to be introduced by:
https://git.yoctoproject.org/yocto-kernel-tools/commit/?id=f73705b23392d3cc584802c9ef5e5394d7461bc4

And later removed by:
https://git.yoctoproject.org/yocto-kernel-tools/commit/?id=1c2fa6c4ecb9fdc3b5b495845141a424b59db33f

In the future, Variscite kindly requests you use the customer support portal: https://www.variscite.com/support/

Regards,
Nate
