### ISSUE TITLE
Create SD card for distro fslc-wayland

### ISSUE THREAD

**Issue by ghost** [varigit/meta-variscite-fsl-community#38]
Hi,

When following the instruction of [Create_an_extended_SD_card_image_using_a_loop_device](https://variwiki.com/index.php?title=Yocto_Build_Release&release=RELEASE_DUNFELL_V1.1_VAR-SOM-MX6#Create_an_extended_SD_card_image_using_a_loop_device), the script is always looking for the directory `build_xwayland`,  which does not exist in my case. Based on the content of the script(https://github.com/varigit/meta-variscite-fslc/blob/b827dc2d265e82ba462e531f5ad1b2e8e0bf84dd/scripts/var_mk_yocto_sdcard/var-create-yocto-sdcard.sh#L25), the reason is trivial, because I initialized the environment with `MACHINE=var-som-mx6 DISTRO=fslc-wayland . setup-environment build_wayland` and only `build_xwayland` and `build_x11` are ever considered. This sounds to me that the fslc-wayland distro is not a real world scenario, so I might be wrong at the first place. Nevertheless, I suggest to have an option to customize the build directory, as it is controlled by the user anyway.

Best regards,

Xiaoyang

**Comment by nsdrude** [comment]
@x19chen I just pushed a patch to the dunfell branch that I cherry-picked from the hardknott branch. Please see: https://github.com/varigit/meta-variscite-fslc/commit/cbdfa5017913eb89a5d54029821579783a29b14b

I agree, we should make this a user option. We have discussed this internally and it's something we'd like to do in the future.

Regards,
Nate
