### ISSUE TITLE
Kirkstone support

### ISSUE THREAD

**Issue by CoRfr** [varigit/meta-variscite-fsl-community#39]
Hi,

as part of an internal update of our firmware, we worked on the Kirkstone (Yocto 4.0) support for `meta-variscite-fslc` & `meta-variscite-hab` repositories.
If you're interested in this support, feel free to use our work at:
- https://github.com/neurio/meta-variscite-fslc/tree/kirkstone
- https://github.com/neurio/meta-variscite-hab/tree/kirkstone

The format `PACKAGECONFIG_remove_mx6` is not allowed anymore in kirkstone, it is now `PACKAGECONFIG:remove:mx6`, which lead to a lot of changes across the repository (see https://github.com/neurio/meta-variscite-fslc/commit/e7889ea3bc294d7bb2d8d2cbb39267a2b6e80ff6 for instance).

Hope it helps

**Comment by nsdrude** [comment]
Hi @CoRfr,

Thank you for the suggestion.

Variscite has split meta-variscite-fslc into [meta-variscite-bsp](https://github.com/varigit/meta-variscite-bsp/) and [meta-variscite-sdk](https://github.com/varigit/meta-variscite-sdk/).

Kirkstone will not be added to meta-variscite-fslc.

Please continue this discussion in the relevant repository mentioned above - we are happy to accept relevant patches that do not trigger large amounts of testing. Patches can be submitted through github pull requests or by opening a ticket in Variscite's customer support portal.

Regards,
Nate
