### ISSUE TITLE
dunfell dart-ul6 sd card boot stuck at - random: crng init done

### ISSUE THREAD

**Issue by topperilya** [varigit/meta-variscite-fsl-community#43]
Hi,

I'm following a guide according to https://variwiki.com/index.php?title=Yocto_Build_Release&release=RELEASE_DUNFELL_V1.1_DART-6UL#local.conf_customization

I created SD card image:

zcat fsl-image-gui-imx6ul-var-dart-20230414144948.rootfs.wic.gz | sudo dd of=/dev/sdb2 bs=1M && sync

and attempting to boot via SD card, the kernel stuck at `random: crng init done`

[    2.957619] wm8731 1-001a: 1-001a supply DCVDD not found, using dummy regulator
[    2.965116] wm8731 1-001a: 1-001a supply DBVDD not found, using dummy regulator
[    2.982088] fsl-sai 202c000.sai: failed to get mclk0 clock: -2
[    2.997072] usb 2-1: new high-speed USB device number 2 using ci_hdrc
[    3.008060] NET: Registered protocol family 26
[    3.014179] NET: Registered protocol family 10
[    3.021631] Segment Routing with IPv6
[    3.025543] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    3.033218] NET: Registered protocol family 17
[    3.037943] can: controller area network core (rev 20170425 abi 9)
[    3.044320] NET: Registered protocol family 29
[    3.048942] can: raw protocol (rev 20170425)
[    3.053244] can: broadcast manager protocol (rev 20170425 t)
[    3.058999] can: netlink gateway (rev 20190810) max_hops=1
[    3.065160] Bluetooth: RFCOMM TTY layer initialized
[    3.070343] Bluetooth: RFCOMM socket layer initialized
[    3.075618] Bluetooth: RFCOMM ver 1.11
[    3.079488] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    3.084814] Bluetooth: BNEP filters: protocol multicast
[    3.090120] Bluetooth: BNEP socket layer initialized
[    3.095099] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[    3.101404] Bluetooth: HIDP socket layer initialized
[    3.106507] lib80211: common routines for IEEE802.11 drivers
[    3.112342] Key type dns_resolver registered
[    3.151289] Registering SWP/SWPB emulation handler
[    3.156458] Loading compiled-in X.509 certificates
[    3.191464] imx_thermal tempmon: Commercial CPU temperature grade - max:95C critical:90C passive:85C
[    3.202523] debugfs: Directory '202c000.sai' with parent 'wm8731audio' already present!
[    3.211526] asoc-simple-card sound: wm8731-hifi <-> 202c000.sai mapping ok
[    3.225331] input: keys as /devices/soc0/keys/input/input3
[    3.233369] rtc-ds1307 1-0068: setting system clock to 2023-04-17T11:59:49 UTC (1681732789)
[    3.242480] ALSA device list:
[    3.245575] usb 2-1: New USB device found, idVendor=1e0e, idProduct=9011, bcdDevice= 3.18
[    3.253844]   #0: wm8731audio
[    3.257430] Waiting for root device /dev/mmcblk0p2...
[    3.262658] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.269915] usb 2-1: Product: SimTech, Incorporated
[    3.274819] usb 2-1: Manufacturer: SimTech, Incorporated
[    3.280206] usb 2-1: SerialNumber: 0123456789ABCDEF
[   33.767060] VSD_3V3: disabling
[   33.770177] gpio_dvfs: disabling
[   69.107153] random: crng init done

my local.conf is:

MACHINE ??= 'imx6ul-var-dart'
DISTRO ?= 'fslc-framebuffer'
PACKAGE_CLASSES ?= 'package_rpm'
EXTRA_IMAGE_FEATURES ?= "debug-tweaks"
USER_CLASSES ?= "buildstats image-mklibs image-prelink"
PATCHRESOLVE = "noop"
BB_DISKMON_DIRS ??= "\
    STOPTASKS,${TMPDIR},1G,100K \
    STOPTASKS,${DL_DIR},1G,100K \
    STOPTASKS,${SSTATE_DIR},1G,100K \
    STOPTASKS,/tmp,100M,100K \
    ABORT,${TMPDIR},100M,1K \
    ABORT,${DL_DIR},100M,1K \
    ABORT,${SSTATE_DIR},100M,1K \
    ABORT,/tmp,10M,1K"
PACKAGECONFIG_append_pn-qemu-system-native = " sdl"
CONF_VERSION = "1"
 
DL_DIR ?= "${BSPDIR}/downloads/"
ACCEPT_FSL_EULA = "1"

what I missed in settings?

Thanks,
Ilya

**Comment by varigigi** [comment]
@topperilya,
the problem is actually here `[ 3.257430] Waiting for root device /dev/mmcblk0p2...`
The SD is somehow corrupted and the rootfs cannot be mounted.
I would suggest flashing again the SD card or trying a different SD card.
I order to get in touch with the R&D team, please consider registering to the [Variscite Customer Portal](https://varisciteportal.axosoft.com/login).
Thanks
Best Regards
Pier

**Comment by topperilya** [comment]
Hi Pier,

Thanks for your answer. I will open case with https://varisciteportal.axosoft.com/login 

I paste the full boot log (below). Maybe it gives more info what is not good in my settings. Also do you know how can I fix:

**Waiting for root device /dev/mmcblk0p2...**  


U-Boot SPL 2018.03-imx_v2018.03_4.14.78_1.0.0_ga_var02+g32670c4e21 (Jun 22 2021 - 07:02:04 +0000)

Part number: VSM-6UL-777B
Assembly: AS1804138745
Date of production: 2018 Aug 22
SOM configuration: NAND
Trying to boot from MMC1
MMC Boot Device: mmc0 (SD)


U-Boot 2018.03-imx_v2018.03_4.14.78_1.0.0_ga_var02+g32670c4e21 (Jun 22 2021 - 07:02:04 +0000)

CPU:   Freescale i.MX6ULL rev1.1 900 MHz (running at 396 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 27C
Reset cause: POR
Board: Variscite DART-6UL
I2C:   ready
DRAM:  512 MiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from MMC... *** Warning - bad CRC, using default environment

Display: VAR-WVGA-LCD (800x480)
Video: 800x480x24
In:    serial
Out:   serial
Err:   serial
switch to partitions #0, OK
mmc0 is current device
Net:   got MAC0 address from fuse: f8:dc:7a:1c:be:5c
FEC0 [PRIME], usb_ether
Error: usb_ether address not set.

Normal Boot
Hit any key to stop autoboot:  0
switch to partitions #0, OK
mmc0 is current device
switch to partitions #0, OK
mmc0 is current device
** Unable to read file /uEnv.txt **
** Unable to read file /boot.scr **
8134256 bytes read in 373 ms (20.8 MiB/s)
Booting from mmc ...
fdt_file=imx6ull-var-dart-6ulcustomboard-nand-sd-card.dtb
34344 bytes read in 20 ms (1.6 MiB/s)
## Flattened Device Tree blob at 83000000
   Booting using the fdt blob at 0x83000000
   Using Device Tree in place at 83000000, end 8300b627

Starting kernel ...

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.4.142+g3a0c66906337 (oe-user@oe-host) (gcc version 9.3.0 (GCC)) #1 SMP PREEMPT Tue Oct 11 07:27:33 UTC 2022
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Variscite DART-6UL with i.MX6ULL, NAND flash & SD card support on VAR-6ULCustomBoard
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 64 MiB at 0x9c000000
[    0.000000] percpu: Embedded 15 pages/cpu s32332 r8192 d20916 u61440
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129920
[    0.000000] Kernel command line: console=ttymxc0,115200 root=/dev/mmcblk0p2 rootwait rw cma=64MB
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 435716K/524288K available (10240K kernel code, 875K rwdata, 3844K rodata, 1024K init, 433K bss, 23036K reserved, 65536K cma-reserved, 0K highmem)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=4 to nr_cpu_ids=1.
[    0.000000]  Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] random: get_random_bytes called from start_kernel+0x2c8/0x48c with crng_init=0
[    0.000000] Switching to timer-based delay loop, resolution 41ns
[    0.000019] sched_clock: 32 bits at 24MHz, resolution 41ns, wraps every 89478484971ns
[    0.000056] clocksource: mxc_timer1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.002733] Console: colour dummy device 80x30
[    0.002804] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=240000)
[    0.002837] pid_max: default: 32768 minimum: 301
[    0.003228] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.003267] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.005244] CPU: Testing write buffer coherency: ok
[    0.006005] CPU0: update cpu_capacity 1024
[    0.006040] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.007562] Setting up static identity map for 0x80100000 - 0x80100060
[    0.007912] rcu: Hierarchical SRCU implementation.
[    0.008708] smp: Bringing up secondary CPUs ...
[    0.008742] smp: Brought up 1 node, 1 CPU
[    0.008764] SMP: Total of 1 processors activated (48.00 BogoMIPS).
[    0.008780] CPU: All CPU(s) started in SVC mode.
[    0.009738] devtmpfs: initialized
[    0.021360] Duplicate name in lcdif@21c8000, renamed to "display#1"
[    0.025718] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[    0.026668] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.026720] futex hash table entries: 256 (order: 2, 16384 bytes, linear)
[    0.032298] pinctrl core: initialized pinctrl subsystem
[    0.034790] NET: Registered protocol family 16
[    0.052879] DMA: preallocated 256 KiB pool for atomic coherent allocations
[    0.055534] cpuidle: using governor menu
[    0.073977] vdd3p0: supplied by regulator-dummy
[    0.074891] cpu: supplied by regulator-dummy
[    0.076271] vddsoc: supplied by regulator-dummy
[    0.100503] No ATAGs?
[    0.100653] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.100689] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.103421] imx6ul-pinctrl 20e0000.iomuxc: initialized IMX pinctrl driver
[    0.104167] imx6ul-pinctrl 2290000.iomuxc-snvs: initialized IMX pinctrl driver
[    0.106367] imx mu driver is registered.
[    0.107374] imx rpmsg driver is registered.
[    0.180358] vgaarb: loaded
[    0.182621] SCSI subsystem initialized
[    0.183812] usbcore: registered new interface driver usbfs
[    0.183943] usbcore: registered new interface driver hub
[    0.184061] usbcore: registered new device driver usb
[    0.186626] i2c i2c-0: IMX I2C adapter registered
[    0.189045] i2c i2c-1: IMX I2C adapter registered
[    0.189966] mc: Linux media interface: v0.10
[    0.190079] videodev: Linux video capture interface: v2.00
[    0.190218] pps_core: LinuxPPS API ver. 1 registered
[    0.190238] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.190289] PTP clock support registered
[    0.193304] MIPI CSI2 driver module loaded
[    0.193439] Advanced Linux Sound Architecture Driver Initialized.
[    0.195312] Bluetooth: Core ver 2.22
[    0.195453] NET: Registered protocol family 31
[    0.195476] Bluetooth: HCI device and connection manager initialized
[    0.195511] Bluetooth: HCI socket layer initialized
[    0.195537] Bluetooth: L2CAP socket layer initialized
[    0.195593] Bluetooth: SCO socket layer initialized
[    0.196808] clocksource: Switched to clocksource mxc_timer1
[    0.197305] VFS: Disk quotas dquot_6.6.0
[    0.197511] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.221701] thermal_sys: Registered thermal governor 'step_wise'
[    0.222338] NET: Registered protocol family 2
[    0.222691] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.224477] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.224569] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.224678] TCP bind hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.224839] TCP: Hash tables configured (established 4096 bind 4096)
[    0.225064] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.225132] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.225540] NET: Registered protocol family 1
[    0.227080] RPC: Registered named UNIX socket transport module.
[    0.227113] RPC: Registered udp transport module.
[    0.227131] RPC: Registered tcp transport module.
[    0.227146] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.227179] PCI: CLS 0 bytes, default 64
[    0.228738] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 5 counters available
[    0.231695] Bus freq driver module loaded
[    0.234177] Initialise system trusted keyrings
[    0.234824] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.251771] NFS: Registering the id_resolver key type
[    0.251850] Key type id_resolver registered
[    0.251869] Key type id_legacy registered
[    0.251971] jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
[    0.253187] fuse: init (API version 7.31)
[    0.343287] Key type asymmetric registered
[    0.343325] Asymmetric key parser 'x509' registered
[    0.343981] io scheduler mq-deadline registered
[    0.344012] io scheduler kyber registered
[    0.351679] pwm-backlight backlight: backlight supply power not found, using dummy regulator
[    0.359847] mxsfb 21c8000.lcdif: 21c8000.lcdif supply lcd not found, using dummy regulator
[    0.376444] sii902x bound to mxs-lcdif from 21c8000.lcdif
[    0.385525] Console: switching to colour frame buffer device 100x30
[    0.410270] mxsfb 21c8000.lcdif: initialized
[    0.414953] mxs-dma 1804000.dma-apbh: initialized
[    0.422011] 2020000.serial: ttymxc0 at MMIO 0x2020000 (irq = 22, base_baud = 5000000) is a IMX
[    1.115108] printk: console [ttymxc0] enabled
[    1.121797] 21e8000.serial: ttymxc1 at MMIO 0x21e8000 (irq = 64, base_baud = 5000000) is a IMX
[    1.132458] 21ec000.serial: ttymxc2 at MMIO 0x21ec000 (irq = 65, base_baud = 5000000) is a IMX
[    1.176579] imx_rngc 2284000.rng: Freescale RNGC registered.
[    1.183029] imx sema4 driver is registered.
[    1.222460] brd: module loaded
[    1.247231] loop: module loaded
[    1.256518] nand: device found, Manufacturer ID: 0x2c, Chip ID: 0xdc
[    1.262987] nand: Micron MT29F4G08ABADAWP
[    1.267061] nand: 512 MiB, SLC, erase size: 128 KiB, page size: 2048, OOB size: 64
[    1.274906] gpmi-nand 1806000.gpmi-nand: use legacy bch geometry
[    1.281602] Scanning device for bad blocks
[    1.296193] random: fast init done
[    2.044921] 5 fixed-partitions partitions found on MTD device gpmi-nand
[    2.051682] Creating 5 MTD partitions on "gpmi-nand":
[    2.056814] 0x000000000000-0x000000200000 : "spl"
[    2.068834] 0x000000200000-0x000000400000 : "uboot"
[    2.088755] 0x000000400000-0x000000500000 : "uboot-env"
[    2.108736] 0x000000500000-0x000001100000 : "kernel"
[    2.128746] 0x000001100000-0x000040000000 : "rootfs"
[    2.133745] mtd: partition "rootfs" extends beyond the end of device "gpmi-nand" -- size truncated to 0x1ef00000
[    2.158851] gpmi-nand 1806000.gpmi-nand: driver registered.
[    2.169792] libphy: Fixed MDIO Bus: probed
[    2.175118] CAN device driver interface
[    2.179839] flexcan 2090000.flexcan: 2090000.flexcan supply xceiver not found, using dummy regulator
[    2.307622] pps pps0: new PPS source ptp0
[    2.313874] libphy: fec_enet_mii_bus: probed
[    2.323221] fec 20b4000.ethernet eth0: registered PHC device 0
[    2.447704] pps pps1: new PPS source ptp1
[    2.455059] fec 2188000.ethernet eth1: registered PHC device 1
[    2.461781] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    2.468508] ehci-pci: EHCI PCI platform driver
[    2.473137] ehci-mxc: Freescale On-Chip EHCI Host driver
[    2.479372] usbcore: registered new interface driver usb-storage
[    2.489392] imx_usb 2184000.usb: No over current polarity defined
[    2.495642] imx_usb 2184000.usb: 2184000.usb supply vbus not found, using dummy regulator
[    2.507937] ci_hdrc ci_hdrc.0: EHCI Host Controller
[    2.512936] ci_hdrc ci_hdrc.0: new USB bus registered, assigned bus number 1
[    2.546943] ci_hdrc ci_hdrc.0: USB 2.0 started, EHCI 1.00
[    2.552828] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[    2.561193] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.568479] usb usb1: Product: EHCI Host Controller
[    2.573376] usb usb1: Manufacturer: Linux 5.4.142+g3a0c66906337 ehci_hcd
[    2.580239] usb usb1: SerialNumber: ci_hdrc.0
[    2.586074] hub 1-0:1.0: USB hub found
[    2.590132] hub 1-0:1.0: 1 port detected
[    2.596427] imx_usb 2184200.usb: No over current polarity defined
[    2.602959] imx_usb 2184200.usb: 2184200.usb supply vbus not found, using dummy regulator
[    2.615798] ci_hdrc ci_hdrc.1: EHCI Host Controller
[    2.621253] ci_hdrc ci_hdrc.1: new USB bus registered, assigned bus number 2
[    2.657104] ci_hdrc ci_hdrc.1: USB 2.0 started, EHCI 1.00
[    2.662981] usb usb2: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[    2.671358] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.678737] usb usb2: Product: EHCI Host Controller
[    2.683636] usb usb2: Manufacturer: Linux 5.4.142+g3a0c66906337 ehci_hcd
[    2.690406] usb usb2: SerialNumber: ci_hdrc.1
[    2.696211] hub 2-0:1.0: USB hub found
[    2.700276] hub 2-0:1.0: 1 port detected
[    2.709543] input: 20cc000.snvs:snvs-powerkey as /devices/soc0/soc/2000000.aips-bus/20cc000.snvs/20cc000.snvs:snvs-powerkey/input/input0
[    2.724401] edt_ft5x06 1-0038: touchscreen probe failed
[    2.732517] input: iMX6UL Touchscreen Controller as /devices/soc0/soc/2000000.aips-bus/2040000.tsc/input/input2
[    2.757035] rtc-ds1307 1-0068: registered as rtc0
[    2.763969] i2c /dev entries driver
[    2.770948] pxp-v4l2 pxp_v4l2: initialized
[    2.780717] imx2-wdt 20bc000.wdog: timeout 60 sec (nowayout=0)
[    2.787853] Bluetooth: HCI UART driver ver 2.3
[    2.792327] Bluetooth: HCI UART protocol H4 registered
[    2.797576] Bluetooth: HCI UART protocol BCSP registered
[    2.802988] Bluetooth: HCI UART protocol LL registered
[    2.808263] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    2.814628] Bluetooth: HCI UART protocol Marvell registered
[    2.820421] usbcore: registered new interface driver btusb
[    2.827946] sdhci: Secure Digital Host Controller Interface driver
[    2.834147] sdhci: Copyright(c) Pierre Ossman
[    2.838976] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.848003] sdhci-esdhc-imx 2190000.usdhc: Got CD GPIO
[    2.887358] mmc0: SDHCI controller on 2190000.usdhc [2190000.usdhc] using ADMA
[    2.899630] caam-snvs 20cc000.caam-snvs: can't get snvs clock
[    2.905560] caam-snvs 20cc000.caam-snvs: violation handlers armed - init state
[    2.917755] usbcore: registered new interface driver usbhid
[    2.923354] usbhid: USB HID core driver
[    2.941783] wm8731 1-001a: 1-001a supply AVDD not found, using dummy regulator
[    2.949592] wm8731 1-001a: 1-001a supply HPVDD not found, using dummy regulator
[    2.957443] wm8731 1-001a: 1-001a supply DCVDD not found, using dummy regulator
[    2.964927] wm8731 1-001a: 1-001a supply DBVDD not found, using dummy regulator
[    2.981910] fsl-sai 202c000.sai: failed to get mclk0 clock: -2
[    2.996969] usb 2-1: new high-speed USB device number 2 using ci_hdrc
[    3.007758] NET: Registered protocol family 26
[    3.013874] NET: Registered protocol family 10
[    3.021307] Segment Routing with IPv6
[    3.025218] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    3.032892] NET: Registered protocol family 17
[    3.037618] can: controller area network core (rev 20170425 abi 9)
[    3.043997] NET: Registered protocol family 29
[    3.048621] can: raw protocol (rev 20170425)
[    3.052919] can: broadcast manager protocol (rev 20170425 t)
[    3.058672] can: netlink gateway (rev 20190810) max_hops=1
[    3.064833] Bluetooth: RFCOMM TTY layer initialized
[    3.070016] Bluetooth: RFCOMM socket layer initialized
[    3.075287] Bluetooth: RFCOMM ver 1.11
[    3.079156] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    3.084485] Bluetooth: BNEP filters: protocol multicast
[    3.089789] Bluetooth: BNEP socket layer initialized
[    3.094768] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[    3.101062] Bluetooth: HIDP socket layer initialized
[    3.106172] lib80211: common routines for IEEE802.11 drivers
[    3.112012] Key type dns_resolver registered
[    3.140367] Registering SWP/SWPB emulation handler
[    3.146409] Loading compiled-in X.509 certificates
[    3.181732] imx_thermal tempmon: Commercial CPU temperature grade - max:95C critical:90C passive:85C
[    3.192826] debugfs: Directory '202c000.sai' with parent 'wm8731audio' already present!
[    3.201831] asoc-simple-card sound: wm8731-hifi <-> 202c000.sai mapping ok
[    3.215128] input: keys as /devices/soc0/keys/input/input3
[    3.223140] rtc-ds1307 1-0068: setting system clock to 2023-04-18T10:28:35 UTC (1681813715)
[    3.232222] ALSA device list:
[    3.235455]   #0: wm8731audio
[    3.239203] Waiting for root device /dev/mmcblk0p2...
[    3.247596] usb 2-1: New USB device found, idVendor=1e0e, idProduct=9011, bcdDevice= 3.18
[    3.255808] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.263065] usb 2-1: Product: SimTech, Incorporated
[    3.268077] usb 2-1: Manufacturer: SimTech, Incorporated
[    3.273399] usb 2-1: SerialNumber: 0123456789ABCDEF
[   33.766937] VSD_3V3: disabling
[   33.770051] gpio_dvfs: disabling
[   69.207050] random: crng init done


Best Regards,
Ilya

**Comment by varigigi** [comment]
@topperilya,
this may be a HW problem related to the SD card detection on the carrier board.
If you are using the DT6ULCarierBoard, you may want to check the CD pin according the schematics available on the [website](https://www.variscite.com/product/system-on-module-som/cortex-a7/dart-6ul-freescale-imx-6ul/#documentation).
If you are using your own carrier, I need to ask HW details that you may don't want to share publicly (better switch to the [Variscite Customer Portal](https://varisciteportal.axosoft.com/login)).
Best Regards
Pier

**Comment by topperilya** [comment]
Hi Pier,

I use PCB VIG-100 MBRev. B

selection switch stand on SD.

Best Regards,
Ilya

**Comment by varigigi** [comment]
@topperilya,
this is not a Variscite board.
To provide suggestions I need to check the manufacturer schematics and you may don't want to share them publicly (better switch to the [Variscite Customer Portal](https://varisciteportal.axosoft.com/login)).
Best Regards
Pier

**Comment by topperilya** [comment]
Hi Pier,

I try to access https://varisciteportal.axosoft.com/login and get:

**Awaiting approval for this account, please contact the administrator.**

My e-mail:
ilya.topper@strukton.com

Can you somehow ask your administrator to help here?

Best Regards,
Ilya

**Comment by topperilya** [comment]
Hi Pier,

I can share these info from the u-boot:

=> mmcinfo
Device: FSL_SDHC
Manufacturer ID: 3
OEM: 5344
Name: SA32G
Bus Speed: 50000000
Mode : SD High Speed (50MHz)
Rd Block Len: 512
SD version 3.0
High Capacity: Yes
Capacity: 29.7 GiB
Bus Width: 4-bit
Erase Group Size: 512 Bytes

=> mmc dev 0
switch to partitions #0, OK
mmc0 is current device

=> mmc dev 1
Card did not respond to voltage select!

Thanks,
Ilya

**Comment by topperilya** [comment]
not resolved
