### ISSUE TITLE
broken link  https://source.codeaurora.org

### ISSUE THREAD

**Issue by srknhcgl** [varigit/meta-variscite-fsl-community#44]
when compiling toolchain since there are still broken links to [https://source.codeaurora.org/](https://source.codeaurora.org/external/imx/uboot-imx.git) compilation fails especially in nxp-imx related files. could you add patch to come accross this problem?
one of the broken link is related to gstreamer1.0
thnx

**Comment by nsdrude** [comment]
@srknhcgl please write the steps you used to reproduce the problem.

Thanks

**Comment by TopperBG** [comment]
@nsdrude what steps, codeaurora doesn't exists anymore.
@srknhcgl use that [variscite-mirrors.inc](https://github.com/varigit/meta-variscite-fslc/blob/d8d4acd399d43de4a2d8c1fac6c7616c47b46873/conf/machine/variscite-mirrors.inc)

**Comment by nsdrude** [comment]
> @nsdrude what steps, codeaurora doesn't exists anymore.

@srknhcgl We have many SOMs, releases, etc. If you provide the steps to reproduce it starting with `repo init ...` we can investigate.

In any case, have you seen: https://variwiki.com/index.php?title=Yocto_Common_Errors#codeaurora.org_migration ?

**Comment by srknhcgl** [comment]
I was using the commands below 
**$ repo init -u https://github.com/varigit/variscite-bsp-platform.git -b kirkstone -m kirkstone-5.15.xml 
$ cd ~/var-fslc-yocto
$ MACHINE=imx8mq-var-dart DISTRO=fslc-xwayland . var-setup-release.sh build_xwayland
$ bitbake meta-toolchain**
sorry guys, I tried to reproduce the issue again but not succeeded.  you can close the issue.

one more thing to say, can you add a message send functionality to https://variwiki.com/. Users may have questions and problems to declare.
