### ISSUE TITLE
master branch status

### ISSUE THREAD

**Issue by gizero** [varigit/meta-variscite-fsl-community#6]
Hi!
I recently started using this meta layer and noticed its master branch is much older than `pyro` and `morty` release branches. I use to develop my projects with an eye to the long term and generally prefer, alongside with stable versions, to keep things working with the latest revision of core tools. This assumes particular importance for bsp-layers. My question is: what's Variscite's plan for supporting ongoing developments on oe-core/yocto? Beside Variscite's official commitment plans on this, I can see some interest from OE experts from the community (see @kraj PRs) to contribute patches to a working (and continuously tested) master branch. I'd really like to have your feedback on these topics: it'd make my upcoming decisions for maintenance plans easier. TIA

**Comment by eranmati** [comment]
Hi Andrea.
As you've noticed, we do not update the master branch of this repository.
We are focused on the release branches and we do not officially support the master branch of oe.
If you want to use the master branch of oe, the best branch choice for of this repository would be the latest release branch (currently pyro).
Contributions from the community are welcome. We review all submitted patches and use them when appropriate, but note that specifically supporting the oe master branch is not our top priority.

Regards,
Eran

**Comment by kraj** [comment]
There is conmunity bsp for these boards maintained by Andreas which is more collaborative I plan to bring these patches to community bsp if nothing works I will just maintain my fork forever after all it's git

**Comment by gizero** [comment]
@kraj Glad to hear your opinion on this! As expected, it's very community-friendly as usual. Also thanks for pointing to the community managed bsp layer: I wasn't aware of that. Unfortunately my focus is on imx7-var-som machine at the moment which I don't see support for in Andreas' layer. I also have some patches around I was planning to contribute.
