### ISSUE TITLE
systemd-gpuconfig missing

### ISSUE THREAD

**Issue by TheTasslehoff** [varigit/meta-variscite-fsl-community#7]
Compiling imx-gpu-viv fails because it needs systemd-gpuconfig.

ERROR: Nothing RPROVIDES 'systemd-gpuconfig' (but /home/tassle/src/yocto-bsp/sources/meta-variscite-fslc/recipes-graphics/imx-gpu/imx-gpu-viv_6.2.2.p0-aarch32.bb RDEPENDS on or otherwise requires it)

**Comment by varigigi** [comment]
the error has been fixed by commit [0bc4c55](https://github.com/varigit/meta-variscite-fslc/commit/0bc4c55faa0437de6f9752b5ad0d409500478b42)
